# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc7b5808a1af0931c2bdccf6abd69f0fdf1edb500a7cc2178f6765280c4a9e81a71cbb4eb46b14c0e85efb5118f5438c9e7fea7402d5320e2883da619476ce33

test:
  secret_key_base: 8c80977ef481826a3d53b053b10f544d5dad5b9225435df71a4e315fe5137a2e633673eacbc4acdbbee0316f75fed3217ec6c9fe6cf241bbdabf11f2e06e97d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
